name: Update docs

on: push

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'   #ssh user name
          server: '${{ secrets.ALIYUN_IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.ALIYUN_SECRECT}} #引用之前创建好的secret
          local_path: './docs'  # 对应我们项目build的文件夹路径
          remote_path: '/root/code/new-blog/'